---
- name: Update packages
  apt: update_cache=yes cache_valid_time=1800

- name: Install security packages
  apt: pkg={{ item }} state=latest
  with_items:
    - apparmor
    - apparmor-easyprof
    - apparmor-profiles
    - apparmor-profiles-extra
    - apparmor-notify
    - apparmor-utils
    - chkrootkit
    - clamtk
    - rkhunter
    - sshguard
    - ufw
    - unhide
    - unhide.rb
